spring:
  config:
    activate:
      on-profile:
        - test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ex_jpa2;MODE=MYSQL;DB_CLOSE_DELAY=-1;   # DB_CLOSE_DELAY=-1: VM이 살아있는 동안 메모리 내 데이터베이스의 내용을 유지
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true          # 쿼리 예쁘게 보기
        use_sql_comments : true   # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT를 표시
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#      path: /h2-console  # default 값

server:
  port: 18080

logging:
  file:
    name: ${env.root-path}/logs
  level:
    org.springframework.web: info
    org.hibernate.type.descriptor.sql: TRACE    # hibernate 로그 자세히
    com:
      zaxxer.hikari.HikariDataSource: info
      hoho.example.kotlinjpa2: debug

env:
  root-path: .