spring:
  config:
    activate:
      on-profile:
        - prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ex_jpa2
    username: ex
    password: expass
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 18081

logging:
  file:
    name: ${env.root-path}/logs
  level:
    org.springframework.web: info
    com:
      zaxxer.hikari.HikariDataSource: error
      hoho.example.kotlinjpa2: info

env:
  root-path: /opt/ex/kotlin-jpa2