spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/h2/ex_jpa_querydsl;MODE=MYSQL;
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments : true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 18080

logging:
  file:
    name: ${env.root-path}/logs
  level:
    org.springframework.web: info
    org.hibernate.type.descriptor.sql: TRACE
    com:
      zaxxer.hikari.HikariDataSource: info
      hoho.example.jpa: debug

env:
  root-path: .